image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production
  - clear

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - cd reddit
  - bundle install

build_job:
  stage: build
  script:
    - echo 'Building'

build_container_reddit:
  stage: build
  image: docker:stable
  before_script:
    - cd reddit
  script:
    - docker build -t reddit:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA .
  environment:
    name: branch/$CI_COMMIT_REF_NAME
  only:
    - branches
  except:
    - master

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

branch_review:
  stage: review
  image: docker:stable
  before_script:
    - cd reddit
  script:
    - docker run --name reddit-$CI_COMMIT_SHORT_SHA -d -p 9292:9292 reddit:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://51.250.13.195:9292
  only:
    - branches
  except:
    - master

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com

clear_review:
  stage: clear
  image: docker:stable
  when: manual
  before_script:
    - cd reddit
  script:
    - docker container kill reddit-$CI_COMMIT_SHORT_SHA
    - docker container rm reddit-$CI_COMMIT_SHORT_SHA
  environment:
    name: branch/$CI_COMMIT_REF_NAME
  only:
    - branches
  except:
    - master
