version: '3.3'
services:
  post_db:
    image: mongo:${post_db_tag}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - post_db:/data/db
    networks:
      - back-network
  ui:
    image: ${USERNAME}/ui:${ui_tag}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${ui_host_port}:${ui_docker_port}
    networks:
      - front-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USERNAME}/post:${post_tag}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - front-network
      - back-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USERNAME}/comment:${comment_tag}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - front-network
      - back-network
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front-network
      - back-network
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front-network
      - back-network
volumes:
  prometheus_data:
  post_db:

networks:
  back-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
